language: ruby

services:
  - docker

env:
  global:
    - secure: XtcHddvEOpBJwQnfzfBn3pjxpsVrYQHTYCAWs1Fh9uB8+vIVdD9iFZj3Cy/7v/5oTwya9mfbMlPvOxpjKUCiwB195n0Z5weluV8L9Tz7JU04AoArfmDaY8nrpzKOuE3JHryOwq9tYIqaMQrF/nCLl1YLNaF25nNA/V9qbYZAOlhHnADneWj0bSQ7KUzJ3zW+pn1+eaYfKs4d89jvUPsYHoSCVnp1A1hSjPbMayAhBpRc2TxL0kVRVupdnUdCXurW9sSVloKVTqpofpTs+IyS5OeUk1VN8Ys6Yxja1aphB40JL/ldBcf4XNKUqhXTU8FDbO3eM/33WkEi+OW6aMWUwzJqypD9WahwQwnR2D7RiTdIF0VxJsVrHeRNFTBSsyQLoh6xAAIpLtYJC4yLF9e8JboL5yb27Zrly2Fs1E5K1RsUMpNcAD+A94po5j14LVE12xptBkvy7anwk3kPZi1hsA2uZpzwAXp4CYAw5ed4J7FuPE97m4n4biOeBD3/DwiiGjrVh+z9Q4auWPVMpccrUncV92IMh2yhYz32CCi9te7fvTncFvQm3S6s0zO6Dvio98+7I8oTX/RxdGcyX4G5NBQIlOuZqG6UzoILvVLfvzuCAwnKpc/arJ5+H3oLkmXHv56mM2MAqHbmmsJK1qxIl7WUkR0oFBY29PwoNCEUsow=
    - secure: sIoPVI3awPlL0gSjxKCzDESsyv6/XD3PWyKIACLGyoU3hqqzwzUh0rlrC74ctYCxU+ftowg0nViIbGS3zIBk+AW1qLqI29ije041HpXO8x4KcsdaN12dXMhUJF+fLTkqCIPUV80vatE1DsMCjEvwLc2b3BSxOjNrgUwD2iObAY0jxh2bGI6K04e4GOQGt3TVSl6CFSOfqiaMSLMrFnTJf0HU0mvrKkV1m8pezZT+qcfYhlWZBTCHRVlSy12aRkWwbH/e5Aspd2iI/vuK+GHYjYw0dUFW8Zw4fFSrV9zXZKaqXyPafFRrJALyJJmDXlPtu9eu0n7ovU+aa0V4uJgk25Ss645KfkKbSiy7vt7xe1Km1BMgPXlwx7N/zdRc8XwHqDtsxNwUbZ3CNlDrbzfm6hW5vesmp4j3qkVzpUL5euW1kDK7tClzS8QwKpXNcOaD3HqIZ48oonn00E0ILLHu6cLkJ9124Tte7rKk7K1ccg9kkzzqXDspW/y9pCCJahK6c5dDAe12Esc8Ksb4CHOX0l1rutfOFMBgUY0YF5tlyBQ+ymqb72UOxE6+GUpBNyLfs2adF6cobwbVFibU7tAuZA8wK0qsJXeZSY/eX7hg93JyXjw5ilBSTerGFJ2xcv9FOenFMnlHWs9nGDg333g2rM3iZhb7EIXHsuLIFkvnDSA=

  matrix:
    - TAG=1.19-alpine-v1
    - TAG=1.18-alpine-v1
    - TAG=1.17-alpine-v12
    - TAG=1.17-alpine-v11
    - TAG=1.17-alpine-v10
    - TAG=1.17-alpine-v9
    - TAG=1.17-alpine-v8
    - TAG=1.17-alpine-v7
    - TAG=1.17-alpine-v6
    - TAG=1.17-alpine-v5
    - TAG=1.17-alpine-v2
    - TAG=1.17-alpine-v1

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - sh build.sh "${TAG}"

after_script:
  - docker images
