name: Monthly Automated Release


on:
  push:
#  schedule:
#    - cron: '0 3 2 * *'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.PAT }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.date.outputs.date }}-test
          release_name: ${{ steps.date.outputs.date }}-test
          body: |
            - automated monthly build & dependencies upgrade
          draft: false
          prerelease: false