name: Docker Push

on:
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                tag: [
                    1.17-alpine-v1,
                    1.17-alpine-v2,
                    1.17-alpine-v5,
                    1.17-alpine-v6,
                    1.17-alpine-v7,
                    1.17-alpine-v8,
                    1.17-alpine-v9,
                    1.17-alpine-v10,
                    1.17-alpine-v11,
                    1.17-alpine-v12,
                    1.18-alpine-v1,
                    1.19-alpine-v1,
                    1.20-alpine-v1,
                    1.21-alpine-v1,
                    1.21-alpine-v1-http,
                    1.22-alpine-v1,
                    1.22-alpine-v1-http,
                    1.23-alpine-v1,
                    1.23-alpine-v1-http,
                ]

        name: TAG-${{ matrix.tag }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: bash build.sh ${{ matrix.tag }}

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'